import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./app.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Al-Qur'an Kita Bersama",
  description: "Generated by create next app",
};

import "primeicons/primeicons.css"
import "primereact/resources/primereact.min.css";
import "primereact/resources/themes/soho-light/theme.css";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
